name: Testing and Linting - Create Secret from .env

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck -y

      - name: Run ShellCheck
        run: shellcheck gh-env-to-repo

  creating_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gh extension
        run: |
          gh extension install endersonmenezes/gh-env-to-repo